# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               ENSAXP
tagline:             'Paris'
description:         'Platerforme collective d'expérimentations numériques en ligne pour les Écoles Nationales Supérieures d'Architecture.
url:                 https://voizer.github.io/ensaxp
baseurl:             '/ensaxp'
paginate:            5

# About/contact
author:
  name:              ENSAXP
  url:               https://google/

# Custom vars
version:             1.0.0
