# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               ENSAXP
tagline:             'Paris Val de Seine'
description:         'Platerforme collective d'expérimentations numériques en ligne pour les Écoles Nationales Supérieures d'Architecture. <a href="https://annuel2.framapad.org/p/iFGWlmLMbf">ENSAXP</a>
url:                 https://voizer.github.io/ensaxp
baseurl:             '/ensaxp'
paginate:            5

# About/contact
author:
  name:              ENSAXP
  url:               https://ensaxp.github.io/

# Custom vars
version:             1.0.0
